// Mengimpor komponen Head dari Next.js
// Digunakan untuk mengatur title, meta description, favicon, dan elemen pada <head>
import Head from 'next/head'

// Mengimpor komponen Image dari Next.js
// Digunakan untuk menampilkan gambar dengan optimasi bawaan Next.js
import Image from 'next/image'

// Mengimpor CSS Module khusus untuk halaman Home
import styles from '../styles/Home.module.css'


// Membuat komponen utama Home
const Home = () => {
  return (

    // Container utama halaman menggunakan class dari CSS Module
    <div className={styles.container}>

      {/* Mengatur informasi yang terdapat pada bagian <head> HTML */}
      <Head>

        {/* Menentukan judul halaman pada tab browser */}
        <title>Create Next App</title>

        {/* Menentukan deskripsi halaman */}
        <meta
          name="description"
          content="Generated by create next app"
        />

        {/* Menentukan favicon atau ikon pada tab browser */}
        <link rel="icon" href="/favicon.ico" />

      </Head>


      {/* Bagian utama isi halaman */}
      <main className={styles.main}>

        {/* Menampilkan judul utama halaman */}
        <h1 className={styles.title}>
          Welcome to my website
        </h1>


        {/* Container untuk kumpulan menu atau kartu navigasi */}
        <div className={styles.grid}>

          {/* Link menuju halaman Demo 1 */}
          <a href="/demo1" className={styles.card}>
            <h2>Demo 1</h2>
            <p>Fetch data from server.</p>
          </a>


          {/* Link menuju halaman Demo 2 */}
          <a href="/demo2" className={styles.card}>
            <h2>Demo 2 &rarr;</h2>
            <p>Fetch data from client</p>
          </a>


          {/* Link menuju halaman eksternal GitHub */}
          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>About &rarr;</h2>
            <p>About me.</p>
          </a>


          {/* Link menuju halaman eksternal dokumentasi Replit */}
          <a
            href="https://docs.replit.com/category/hosting"
            className={styles.card}
          >
            <h2>Contact &rarr;</h2>
            <p>
              Contact me
            </p>
          </a>

        </div>
      </main>


      {/* Bagian footer atau bagian bawah halaman */}
      <footer className={styles.footer}>

        {/* 
          Link menuju halaman Replit.
          target="_blank" digunakan untuk membuka link di tab baru.
          rel="noopener noreferrer" digunakan sebagai pengamanan
          saat membuka halaman eksternal di tab baru.
        */}
        <a
          href="/__repl"
          target="_blank"
          rel="noopener noreferrer"
        >

          {/* Menampilkan teks Built on */}
          Built on

          {/* Container untuk logo Replit */}
          <span className={styles.logo}>

            {/* Menampilkan gambar logo Replit */}
            <Image
              src="/replit.svg"
              alt="Replit Logo"
              width={20}
              height={18}
            />

          </span>

          {/* Menampilkan teks Replit */}
          Replit

        </a>
      </footer>

    </div>
  )
}


// Mengekspor komponen Home agar dapat digunakan sebagai halaman utama
export default Home
